### ISSUE TITLE
`--root` option modifies host system instead of target environment

### ISSUE THREAD

**Issue by Tachi107** [cromerc/opensysusers#4]
Hi, I'm reporting here an issue which has been reported downstream in Debian a while ago (<https://bugs.debian.org/1055517>).

On Tue, 07 Nov 2023 19:38:25 +0100 Ansgar <ansgar@debian.org> wrote:
> opensysusers doesn't really implement the `--root` option (though it pretends a bit).  Functions like `add_group` always access `/etc/group` and use tools like `groupadd`:
> 
> ```sh
> grep -q "^$1:" /etc/group || groupadd -r "$1"
> ```
> 
> So they will always modify the host system, even when supposed to operate on some chroot environment.
> 
> Applying changes intended for some other environment to the host system looks like a potential security issue.

**Comment by Tachi107** [comment]
Hi, do you think a patch like this would suffice?

```diff
diff --git a/sysusers b/sysusers
index 05f7a70..db2b4ea 100755
--- a/sysusers
+++ b/sysusers
@@ -15,9 +15,9 @@ warninvalid() {
 add_group() {
 	# add_group <name> <id>
 	if [ "$2" = '-' ]; then
-		grep -q "^$1:" /etc/group || groupadd -r "$1"
-	elif ! grep -q "^$1:\|^[^:]*:[^:]*:$2:[^:]*$" /etc/group; then
-		groupadd -g "$2" "$1"
+		grep -q "^$1:" "$root/etc/group" || groupadd --prefix "$root" -r "$1"
+	elif ! grep -q "^$1:\|^[^:]*:[^:]*:$2:[^:]*$" "$root/etc/group"; then
+		groupadd --prefix "$root" -g "$2" "$1"
 	fi
 }
 
@@ -25,11 +25,11 @@ add_user() {
 	# add_user <name> <id> <gecos> <home>
 	if ! id "$1" >/dev/null 2>&1; then
 		if [ "$2" = '-' ]; then
-			useradd -rc "$3" -g "$1" -d "$4" -s '/sbin/nologin' "$1"
+			useradd --prefix "$root" -rc "$3" -g "$1" -d "$4" -s '/sbin/nologin' "$1"
 		else
-			useradd -rc "$3" -u "$2" -g "$1" -d "$4" -s '/sbin/nologin' "$1"
+			useradd --prefix "$root" -rc "$3" -u "$2" -g "$1" -d "$4" -s '/sbin/nologin' "$1"
 		fi
-		passwd -l "$1" >/dev/null 2>&1
+		passwd --prefix "$root" -l "$1" >/dev/null 2>&1
 	fi
 }
 
@@ -102,10 +102,10 @@ parse_string() {
 		m)
 			add_group "${id}" '-'
 			if id "${name}" >/dev/null 2>&1; then
-				usermod -a -G "${id}" "${name}"
+				usermod --prefix "$root" -a -G "${id}" "${name}"
 			else
-				useradd -r -g "${id}" -s '/sbin/nologin' "${name}"
-				passwd -l "${name}" >/dev/null 2>&1
+				useradd --prefix "$root" -r -g "${id}" -s '/sbin/nologin' "${name}"
+				passwd --prefix "$root" -l "${name}" >/dev/null 2>&1
 			fi
 		;;
 		r)
```

**Comment by cromerc** [comment]
From the looks of it this should be enough to fix it. Open a pull request and I will merge it.

**Comment by Tachi107** [comment]
Yes, I've applied this patch to the Debian package of opensysusers, and from my limited [testing] it seems that the issue was fixed.

I'll submit this as a pull request later today.

[testing]: https://salsa.debian.org/debian/opensysusers/-/blob/debian/latest/debian/tests/root
